# Generated by Django 4.0.3 on 2022-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_ID', models.CharField(max_length=300)),
                ('VARIENT_ID', models.CharField(max_length=300)),
                ('BATCH_ID', models.CharField(max_length=300)),
                ('BATCH_STOCK', models.IntegerField()),
                ('BATCH_NUMBER', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_ID', models.CharField(max_length=300)),
                ('CATEGORY_NAME', models.CharField(max_length=300)),
                ('IMAGES', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='log_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.CharField(max_length=300)),
                ('admin_name', models.CharField(max_length=300)),
                ('changes_type', models.CharField(max_length=300)),
                ('changes_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='product_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_ID', models.CharField(max_length=300)),
                ('VARIENT_ID', models.CharField(max_length=300)),
                ('PRODUCT_NAME', models.CharField(max_length=300)),
                ('IMAGES', models.CharField(max_length=300)),
                ('CATEGORY_ID', models.CharField(max_length=300)),
                ('CATEGORY', models.CharField(max_length=300)),
                ('VARIENTS', models.CharField(max_length=300)),
                ('PRICE', models.CharField(max_length=300)),
                ('VARIENT_STOCK', models.CharField(max_length=300)),
                ('TOTAL_STOCK', models.IntegerField()),
                ('SIBLING_PRODUCT', models.CharField(max_length=300)),
                ('BENEFITS', models.TextField()),
                ('INGREDIENTS', models.TextField()),
                ('HOW_TO_USE', models.TextField()),
                ('HOW_WE_MAKE_IT', models.TextField()),
                ('NUTRITIONAL_INFO', models.TextField()),
                ('SKU_CODE', models.CharField(max_length=300)),
                ('HSN_CODE', models.CharField(max_length=300)),
                ('BATCH_ID_LATEST', models.CharField(max_length=300)),
                ('BATCH_NUMBER_LATEST', models.CharField(max_length=300)),
            ],
        ),
    ]
