# Generated by Django 4.0.3 on 2022-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_view',
            name='COLOR_CODE',
            field=models.CharField(default='#ffffff', max_length=300),
            preserve_default=False,
        ),
    ]
