# Generated by Django 4.0.3 on 2022-09-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_category_view_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_view',
            name='BATCH_ID_LATEST',
        ),
        migrations.RemoveField(
            model_name='product_view',
            name='BATCH_NUMBER_LATEST',
        ),
    ]
