# Generated by Django 4.0.3 on 2022-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_remove_product_view_batch_id_latest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_ID', models.CharField(max_length=300)),
                ('VARIENT_ID', models.CharField(max_length=300)),
            ],
        ),
    ]
