# Generated by Django 4.0.3 on 2022-09-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_product_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_view',
            name='NUTRITIONAL_UNIT',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
