# Generated by Django 4.0.3 on 2022-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_product_view_nutritional_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_view',
            name='HSN_CODE',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
